---
title: "Law of returns"
author: "Deependra Dhakal"
date: "`r Sys.Date()`"
output: 
  tint::tintBook:
    keep_tex: true
tables: yes
bibliography: [../bibliographies.bib]
link-citations: yes
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

```{r setup, include=FALSE}
library(tint)
library(knitr)
require(tidyverse)
set.seed(453)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE, 
                      cache.extra = packageVersion('tint'), 
                      message = FALSE, warning = FALSE, fig.width = 5)
options(htmltools.dir.version = FALSE) 
options(knitr.table.format = "latex")
options(knitr.kable.NA = "", digits = 2)
options(kableExtra.latex.load_packages = FALSE)
```

## Law of returns

```{r law-of-returns}
ppr_constant <- readxl::read_xlsx("./data/concepts_of_economics.xlsx", 
                               sheet = "ppr_constant", col_names = TRUE)

ppr_constant %>% 
  Hmisc::bezier(evaluation = 100) %>%
  as_tibble() %>% 
  ggplot(aes(y = y, x = x)) +
  labs(y = "Output (Wheat yield tons)", 
       x = "Input (Planting density)") +
  geom_line(size = 1.0)

ppr_increasing <- readxl::read_xlsx("./data/concepts_of_economics.xlsx", 
                               sheet = "ppr_increasing", col_names = TRUE)

ppr_increasing %>% 
  Hmisc::bezier(evaluation = 100) %>%
  as_tibble() %>% 
  ggplot(aes(y = x, x = y)) +
  labs(y = "Output (Wheat yield tons)", 
       x = "Input (Planting density)") +
  geom_line(size = 1.0)

ppr_decreasing <- readxl::read_xlsx("./data/concepts_of_economics.xlsx", 
                               sheet = "ppr_decreasing", col_names = TRUE)

ppr_decreasing %>% 
  Hmisc::bezier(evaluation = 100) %>%
  as_tibble() %>% 
  ggplot(aes(y = x, x = y)) +
  labs(y = "Output (Wheat yield tons)", 
       x = "Input (Planting density)") +
  geom_line(size = 1.0)

ppr_negative <- readxl::read_xlsx("./data/concepts_of_economics.xlsx", 
                               sheet = "ppr_negative", col_names = TRUE)

ppr_negative[-1,] %>% 
  Hmisc::bezier(evaluation = 100) %>%
  as_tibble() %>% 
  ggplot(aes(y = y, x = x)) +
  labs(y = "Output (Wheat yield tons)", 
       x = "Input (Planting density)") +
  geom_line(size = 1.0)
```

