---
author: Deependra Dhakal
fontsize: 12pt
title: Production and cost
date: \today
institute:
  - GAASC, Baitadi
  - Tribhuwan University 
output: 
  binb::iqss:
    keep_tex: true
    slide_level: 2
    includes:
      in_header: iqss_beamer_header.tex
classoption: "aspectratio=169"
bibliography: [./../bibliography/bibliographies.bib]
---

```{r setup, include=FALSE}
library(knitr)
require(tidyverse)
set.seed(453)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE, 
                  message = FALSE, warning = FALSE,
                  out.width = "45%", cache = TRUE)
options(knitr.table.format = "latex")
options(knitr.kable.NA = "", digits = 2, knitr.kable.NAN = "")
options(kableExtra.latex.load_packages = FALSE)
source("./../scripts/supply-demand-surplus.R")
source("./../scripts/graphics.R")
# require(extrafont) # requires for graphics.R
# require(extrafontdb)
# extrafont::loadfonts()
# extrafont::font_import()
```

# Cost concepts

## Background

- A farmer can increase his income by one of two ways:
  1. Increasing the production
  2. Reducing the cost of production
- Normally in competitive market, prices are not in the control of individual farmer, hist additional production must, therefore, sell at same or even lower price.
- Additionally, the cost of producing extra units of produce might involve higher costs.
- The second alternative is to reduce the cost of production.
- Often the cost of production is a policy issue when producer complain about not covering cost of production from the price they receive for their produce.

## Cash cost and non-cash cost

- In economics cost means the total efforts involved in the production of a commodity while expense of production only signify only money costs.
- Cash costs are incurred when resources are purchased and used immediately in the production process.
- Non-cash cost consist of depreciation and payments to resources owned by the farmers e.g., depreciation on tractor, equipment, buildings, payment made to the farmer himself or family labor, management and owned capital.

## Total cost

- Fixed costs plus variable costs equal total costs. Total costs are required for computing net revenue. Net revenue is equal to total revenue less total cost.
- Whether a particular cost item will be considered as fixed or variable one depends upon whether the input concerned is fixed or variable for the problem under consideration.
- During long run planning period all inputs are variable. Thus in long run there are no fixed costs.
- Total cost = Fixed cost + Variable cost

## Marginal cost

- The additional cost of doing a little bit more (or 1 unit more if a unit can be measured) of an activity.
- How do you make a rational decision about when the alarm should go off? What you have to do is to weigh up the costs and benefits of additional sleep. Each extra minute in bed gives you more sleep (the marginal benefit), but gives you more of a rush when you get up (the marginal cost).
- The decision is therefore based on the costs and benefits of extra sleep, not on the total costs and benefits of a whole night’s sleep.

## Characteristics of marginal cost

## Opportunity cost

- The farm resources have alternative uses.
- The price that will be required to prevent the transferance of factors to other uses is called "opportunity cost" or "alternative cost".
- The price which should be put on any input is therefore the return which must be given up in the next best alternative use.
- Thus every resource used in production has one true cost: opportunity cost.
- Suppose a farmer has 40 kgs of fertilizer; it adds Rs 250 to the total revenue from wheat and Rs 200 to the revenue from barley. If he fertilizes barley, his opportunity cost is Rs 250, which he has foregone on wheat. If he fertilizes wheat, his opportunity cost is Rs 200, foregone on barley.

##

- Thus once purchased, market price of input becomes irrelevant to the problem of its allocation among alternative uses.
- In case of durable resources such as machinery or land which are used in production, the opportunity cost is defined to be the amount that total capital investment could earn if invested in its best alternative use.
- For simplest case, the opportunity cost will be interest that a deposit of money in a bank would fetch.

## Return concepts

- Gross return = Total production $\times$ price
- Returns to fixed farm resources(or returns over variable costs) = Gross returns - Variable cost
- Net return = Gross return - Total cost

## Rational decision

- Doing more of an activity if its marginal benefit exceeds its marginal cost and doing less if its marginal cost exceeds its marginal benefit.
- Rational decisions are made with rational choices; that involve weighing up the benefit of any activity against its opportunity cost.

## Cost function

- The total cost curve or cost function represents the functional relationship between output and total cost.
- It shows the change in cost structure when we produce different quantities of a commodity.
- The exact nature of the Total Cost function depends on the nature of the corresponding production function, provided that the price which the producer pays for inputs does not change as the quantity of inputs purchased changes.

## Relationship between production function and total cost function


# Relationship between various costs

## TC, TFC and TVC

Fig. 5.3 and explaination.


## ATC, AFC and AVC

Fig. 5.4 and explaination.

## Relationship between average and marginal cost

Fig. 5.5 and explaination.

# Bibliography

## For more information
