---
author: Deependra Dhakal
fontsize: 12pt
title: "Concept of cooperatives"
date: \today
institute:
  - GAASC, Baitadi
  - Tribhuwan University 
output: 
  binb::iqss:
    keep_tex: true
    slide_level: 2
    includes:
      in_header: iqss_beamer_header.tex
classoption: "aspectratio=169"
---

```{r setup, include=FALSE}
library(knitr)
require(tidyverse)
set.seed(453)
# invalidate cache when the package version changes
knitr::opts_chunk$set(tidy = FALSE, echo = FALSE, 
                  message = FALSE, warning = FALSE,
                  out.width = "45%", cache = TRUE)
options(knitr.table.format = "latex")
options(knitr.kable.NA = "", digits = 2, knitr.kable.NAN = "")
options(kableExtra.latex.load_packages = FALSE)
```

# Introduction

## Definition

- A cooperative is an autonomous association of people who voluntarily cooperate for their mutual social, economic, and cultural benefit. 
- Includes non-profit community organizations and businesses that are owned and managed by the people who use its services (a consumer cooperative) or by the people who work there (a worker cooperative) or by the people who live there (a housing cooperative).
- In short: "a jointly owned enterprise engaging in the production or distribution of goods or the supplying of services, operated by its members for their mutual benefit, typically organized by consumers or farmers."
- Co-operatives frequently have social goals which they aim to accomplish by investing a proportion of trading profits back into their communities.
- The Rochdale Society of Equitable Pioneers, founded in 1844, is usually considered the first successful cooperative enterprise. They set up the society to open their own store selling food items they could not otherwise afford.

## Cooperative values

- Self help
- Self accountability
- Democracy
- Equality
- Equity
- Solidarity
- Honesty
- Openness
- Social responsibility
- Caring for others

## Principles^[Adopted by the international cooperative alliance in 1995]

\footnotesize

1. Voluntary and open membership
  - Cooperatives are open to all people willing to volunteer to use its services and willing to accept the responsibilities of membership, without gender, social, racial, political or religious discrimination.
2. Democratic member control
  - Those who buy the goods or use the services of the cooperatives also actively participate in setting policies and making decisions.
3. Members' economic participation
  - Members contribute equally to and democratically control the capital of the cooperative.
  - Benefits are distributed proportionally to each member's level of participation in the cooperative, for instance, by a dividend on sales or purchases, rather than according to capital invested.
  
##

\footnotesize

4. Autonomy and independence
- Cooperatives are autonomous, self-help organizations controlled by their members.
- If they enter into agreements with other organizations, including governments, or raise capital from external sources, they maintain their cooperative autonomy.
5. Education, training and information
- Co-operatives provide education and training for their members, elected representatives, managers, and employees so they can contribute effectively to the development of their co-operatives.

##

6. Cooperation among cooperatives
- Co-operatives serve their members most effectively and strengthen the co-operative movement by working together through local, national, regional and international structures.
7. Concern for community
- Co-operative work for the sustainable development of their communities through policies approved by their members.

# Organization/structures

##


## Types of farmer cooperative

\footnotesize

1. Production cooperatives
- Farmer cooperatives for agricultural production such as milk, fruits and vegetables, poultry, etc. fall into this category.
2. Supply cooperatives
- Farm supply cooperatives are vital for the dependable supply of farm inputs such as farm machinery, equipment, fertilizers, housing materials, livestock feed, seed and petroleum products.
- They may also handle items such as lawn equipment, food items, or necessary items for gardening.
- Cooperative endeavors such as feed mills, farm machinery, and fertilizer plants can be established at the regional or national level, whereas the farm supply depot can be established at the local level.

##

3. Service cooperatives
- Set up for special services such as credit services, telephone/electric service, insurance services, irrigation services, grain banks, trucking, artificial insemination, cotton ginning, ginger drying, rice drying, etc.
- Service cooperatives may also provide items such as chemicals, diesel, oil, gas, feed, seedlings, and seeds to its members.
- Soil testing, crop scouting, and land leveling are other services a service cooperative may provide to its members.
4. Credit
- Members should be able to obtain the required credit from their cooperative, and the cooperative should be able to deliver the credit and accept deposits from its members in order to build some capital for itself.

##

4. Processing
- Farmer's cooperatives for processing agricultural commodities such as fruits, vegetables, spices and beverages crops. They are important to minimize post harvest losses and increase the income of the farmers.
5. Guidance (which includes education, training and extension services): 
- The members should be able to receive spontaneous guidance and advice from their cooperative, and the cooperative should be able to deliver expert advice to the members
6. Marketing cooperatives
- Includes commodities or commodity groups such as cotton, dairy, fruit and vegetables, poultry, and livestock marketing cooperatives.
- Primary objectives is marketing the farm produce of its members. 
- As marketing is difficult task for individual farmers, establishing a marketing cooperative is very important for commercialized agricultural development and to maintain the farm profit.

# Roles of cooperative in commercial farming

##

\footnotesize

- Agricultural cooperatives play an important role in food production and distribution, and in supporting long-term food security. 
- Agricultural cooperatives play an important role in supporting small agricultural producers and marginalized groups such as young people and women. 
<!-- - Empower members economically and socially and create sustainable rural employment through business models that are resilient to economic and environmental shocks. -->
- Cooperatives offer small agricultural producers opportunities and a wide range of services, including improved access to,
  - markets, 
  - natural resources, 
  - information, 
  - communications, 
  - technologies, 
  - credit, 
  - training, and 
  - warehouses. 

##

\footnotesize

- Facilitate smallholder producers' participation in decision-making at all levels, support them in securing land-use rights, and negotiate better terms for engagement in contract farming and lower prices for agricultural inputs such as seeds, fertilizer and equipment. 
- Through this support, smallholder producers can secure their livelihoods and play a greater role in meeting the growing demand for food on local, national and international markets, thus contributing to poverty alleviation, food security and the eradication of hunger. 
- Agricultural cooperatives also promote the participation of women in economic production
  - women are able to unite in solidarity and provide a network of mutual support to overcome cultural restrictions to pursuing commercial economic activities. 
  - For example, women-only cooperatives in South Asia facilitate economic independence and improve the social standing of women through their active participation in businesses and management.

# Cooperatives laws and by-laws

## Acts, policies and laws

- Cooperative act, 2048 BS
- Cooperative regulation, 2049 BS
- Cooperative registration operation, auditing, monitoring and execution standards, 2068 BS
- National cooperative policy, 2069 BS
- Cooperative organization unification related guideline, 2070 BS
- Cooperative act, 2074 BS^[Refer to lecture slides in Nepali for details]

## National cooperative federation of Nepal (NCFN)

- Established in June 20, 1993 under the Co-operative Act, 1992 
- The apex body of the cooperative movement of all types and levels of cooperatives organized on the basis of universally accepted cooperative values and principles. 
- Represents in government, national and international forum on behalf of all cooperatives. 
- There are more than 24 thousand Primary Cooperatives, 223 District Level Cooperative Unions, 14 Central Cooperative Unions and 1 National Cooperative Bank under the umbrella of NCFN. 
- There are more than 3.2 million cooperative members including around 42 percent women membership. (Source: Department of Cooperatives, July 15, 2011)
- NCFN is a member of International Cooperative Alliance (ICA), Geneva. It is also affiliated with the Network for the Development of Agricultural Cooperatives (NEDAC), Thailand.

